# Generated by Django 3.2.25 on 2024-11-03 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=200)),
                ('pesticide_term', models.CharField(blank=True, max_length=100, null=True)),
                ('food_term', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(null=True)),
                ('results_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '검색 로그',
                'verbose_name_plural': '검색 로그',
                'db_table': 'search_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='limitconditioncode',
            options={'verbose_name': '제한조건 코드', 'verbose_name_plural': '제한조건 코드'},
        ),
        migrations.AlterModelOptions(
            name='pesticidelimit',
            options={'verbose_name': '농약 잔류허용기준', 'verbose_name_plural': '농약 잔류허용기준'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '사용자', 'verbose_name_plural': '사용자'},
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='pesticidelimit',
            index=models.Index(fields=['pesticide_name_kr'], name='pesticide_l_pestici_ce9430_idx'),
        ),
        migrations.AddIndex(
            model_name='pesticidelimit',
            index=models.Index(fields=['pesticide_name_en'], name='pesticide_l_pestici_458c40_idx'),
        ),
        migrations.AddIndex(
            model_name='pesticidelimit',
            index=models.Index(fields=['food_name'], name='pesticide_l_food_na_f9a2cf_idx'),
        ),
    ]
