# Generated by Django 3.2.25 on 2025-01-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20241116_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitconditioncode',
            name='code',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
