# Generated by Django 3.2.25 on 2025-01-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20250111_2253'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pesticidelimit',
            name='pesticide_l_pestici_ce9430_idx',
        ),
        migrations.RemoveIndex(
            model_name='pesticidelimit',
            name='pesticide_l_pestici_458c40_idx',
        ),
        migrations.RemoveIndex(
            model_name='pesticidelimit',
            name='pesticide_l_food_na_f9a2cf_idx',
        ),
        migrations.AddIndex(
            model_name='pesticidelimit',
            index=models.Index(fields=['pesticide_name_kr', 'food_name'], name='pesticide_l_pestici_32cb2a_idx'),
        ),
        migrations.AddIndex(
            model_name='pesticidelimit',
            index=models.Index(fields=['pesticide_name_en', 'food_name'], name='pesticide_l_pestici_d530c1_idx'),
        ),
    ]
