# Generated by Django 3.2.25 on 2025-03-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_certificateofanalysis_applicant_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateofanalysis',
            name='analytical_method',
            field=models.TextField(blank=True, null=True, verbose_name='검정방법'),
        ),
        migrations.AlterField(
            model_name='certificateofanalysis',
            name='analytical_purpose',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='검정목적'),
        ),
        migrations.AlterField(
            model_name='certificateofanalysis',
            name='analyzed_items',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='검정항목'),
        ),
        migrations.AlterField(
            model_name='certificateofanalysis',
            name='applicant_address',
            field=models.TextField(blank=True, null=True, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='certificateofanalysis',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='신청인명/기관명'),
        ),
        migrations.AlterField(
            model_name='certificateofanalysis',
            name='applicant_tel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='certificateofanalysis',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='증명서번호'),
        ),
        migrations.AlterField(
            model_name='certificateofanalysis',
            name='producer_info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='생산자/수거지'),
        ),
        migrations.AlterField(
            model_name='certificateofanalysis',
            name='sample_description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='검정품목'),
        ),
        migrations.AlterField(
            model_name='certificateofanalysis',
            name='sample_quantity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='시료점수 및 중량'),
        ),
        migrations.AlterField(
            model_name='certificateofanalysis',
            name='test_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='검정종료일'),
        ),
        migrations.AlterField(
            model_name='certificateofanalysis',
            name='test_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='검정시작일'),
        ),
    ]
