# Generated by Django 3.2.25 on 2025-03-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20250309_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesticideresult',
            name='calculated_result',
        ),
        migrations.RemoveField(
            model_name='pesticideresult',
            name='is_consistent',
        ),
        migrations.RemoveField(
            model_name='pesticideresult',
            name='korea_mrl',
        ),
        migrations.AddField(
            model_name='pesticideresult',
            name='db_calculated_result',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DB 기준 계산 결과'),
        ),
        migrations.AddField(
            model_name='pesticideresult',
            name='db_korea_mrl',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='DB 잔류허용기준(mg/kg)'),
        ),
        migrations.AddField(
            model_name='pesticideresult',
            name='is_pdf_consistent',
            field=models.BooleanField(default=True, verbose_name='PDF 검토의견 일치여부'),
        ),
        migrations.AddField(
            model_name='pesticideresult',
            name='pdf_calculated_result',
            field=models.CharField(default='적합', max_length=20, verbose_name='PDF 기준 계산 결과'),
        ),
        migrations.AddField(
            model_name='pesticideresult',
            name='pdf_korea_mrl',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='PDF 잔류허용기준(mg/kg)'),
        ),
        migrations.AddField(
            model_name='pesticideresult',
            name='pesticide_name_match',
            field=models.BooleanField(default=True, verbose_name='농약성분명 일치여부'),
        ),
        migrations.AddField(
            model_name='pesticideresult',
            name='standard_pesticide_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='표준 농약성분명'),
        ),
        migrations.AlterField(
            model_name='pesticideresult',
            name='pdf_result',
            field=models.CharField(max_length=20, verbose_name='PDF 검토의견'),
        ),
    ]
