# Generated by Django 3.2.25 on 2025-07-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('query_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '게스트 세션',
                'verbose_name_plural': '게스트 세션',
                'db_table': 'guest_sessions',
            },
        ),
        migrations.AddIndex(
            model_name='guestsession',
            index=models.Index(fields=['session_key'], name='guest_sessi_session_b26f6e_idx'),
        ),
        migrations.AddIndex(
            model_name='guestsession',
            index=models.Index(fields=['ip_address', 'created_at'], name='guest_sessi_ip_addr_e145ca_idx'),
        ),
    ]
