# Django의 Custom Command입니다, 정부에서 제공하는 농약스펙에 내가 찾는 식품명이 존재하지 않을 경우 카테고리에서 대표 식품으로 조회하는 용도.
# python manage.py import_food_categories 실행하면, DB에 데이터가 업로드 되는 것까지가 이 코드의 역할

from django.core.management.base import BaseCommand
from api.models import FoodCategory

class Command(BaseCommand):
    help = '식품 분류 데이터 가져오기'

    def handle(self, *args, **kwargs):
        FoodCategory.objects.all().delete()

        categories_data = [
            # 곡류
            {'main_category': '곡류', 'food_name': '귀리'},
            {'main_category': '곡류', 'food_name': '기장'},
            {'main_category': '곡류', 'food_name': '메밀'},
            {'main_category': '곡류', 'food_name': '밀'},
            {'main_category': '곡류', 'food_name': '보리'},
            {'main_category': '곡류', 'food_name': '수수'},
            {'main_category': '곡류', 'food_name': '쌀'},
            {'main_category': '곡류', 'food_name': '아마란스'},
            {'main_category': '곡류', 'food_name': '옥수수'},
            {'main_category': '곡류', 'food_name': '율무'},
            {'main_category': '곡류', 'food_name': '조'},
            {'main_category': '곡류', 'food_name': '퀴노아'},
            {'main_category': '곡류', 'food_name': '트리티케일'},
            {'main_category': '곡류', 'food_name': '피'},
            {'main_category': '곡류', 'food_name': '호밀'},

            # 서류
            {'main_category': '서류', 'food_name': '감자'},
            {'main_category': '서류', 'food_name': '고구마'},
            {'main_category': '서류', 'food_name': '곤약'},
            {'main_category': '서류', 'food_name': '마'},
            {'main_category': '서류', 'food_name': '마카'},
            {'main_category': '서류', 'food_name': '야콘'},
            {'main_category': '서류', 'food_name': '카사바'},
            {'main_category': '서류', 'food_name': '토란'},

            # 두류
            {'main_category': '두류', 'food_name': '강낭콩'},
            {'main_category': '두류', 'food_name': '녹두'},
            {'main_category': '두류', 'food_name': '대두'},
            {'main_category': '두류', 'food_name': '동부'},
            {'main_category': '두류', 'food_name': '렌즈콩'},
            {'main_category': '두류', 'food_name': '리마콩'},
            {'main_category': '두류', 'food_name': '완두'},
            {'main_category': '두류', 'food_name': '이집트콩'},
            {'main_category': '두류', 'food_name': '작두콩'},
            {'main_category': '두류', 'food_name': '잠두'},
            {'main_category': '두류', 'food_name': '제비콩'},
            {'main_category': '두류', 'food_name': '팥'},
            {'main_category': '두류', 'food_name': '피전피'},

            # 견과종실류 - 땅콩 또는 견과류
            {'main_category': '견과종실류', 'sub_category': '견과류', 'food_name': '땅콩'},
            {'main_category': '견과종실류', 'sub_category': '견과류', 'food_name': '개암'},
            {'main_category': '견과종실류', 'sub_category': '견과류', 'food_name': '도토리'},
            {'main_category': '견과종실류', 'sub_category': '견과류', 'food_name': '마카다미아'},
            {'main_category': '견과종실류', 'sub_category': '견과류', 'food_name': '밤'},
            {'main_category': '견과종실류', 'sub_category': '견과류', 'food_name': '브라질넛'},
            {'main_category': '견과종실류', 'sub_category': '견과류', 'food_name': '아몬드'},
            {'main_category': '견과종실류', 'sub_category': '견과류', 'food_name': '은행'},
            {'main_category': '견과종실류', 'sub_category': '견과류', 'food_name': '잣'},
            {'main_category': '견과종실류', 'sub_category': '견과류', 'food_name': '케슈너트'},
            {'main_category': '견과종실류', 'sub_category': '견과류', 'food_name': '피스타치오'},
            {'main_category': '견과종실류', 'sub_category': '견과류', 'food_name': '피칸'},
            {'main_category': '견과종실류', 'sub_category': '견과류', 'food_name': '호두'},

            # 견과종실류 - 유지종실류
            {'main_category': '견과종실류', 'sub_category': '유지종실류', 'food_name': '달맞이꽃씨'},
            {'main_category': '견과종실류', 'sub_category': '유지종실류', 'food_name': '대마씨'},
            {'main_category': '견과종실류', 'sub_category': '유지종실류', 'food_name': '들깨'},
            {'main_category': '견과종실류', 'sub_category': '유지종실류', 'food_name': '면실'},
            {'main_category': '견과종실류', 'sub_category': '유지종실류', 'food_name': '올리브'},
            {'main_category': '견과종실류', 'sub_category': '유지종실류', 'food_name': '유채씨'},
            {'main_category': '견과종실류', 'sub_category': '유지종실류', 'food_name': '참깨'},
            {'main_category': '견과종실류', 'sub_category': '유지종실류', 'food_name': '팜'},
            {'main_category': '견과종실류', 'sub_category': '유지종실류', 'food_name': '해바라기씨'},
            {'main_category': '견과종실류', 'sub_category': '유지종실류', 'food_name': '호박씨'},
            {'main_category': '견과종실류', 'sub_category': '유지종실류', 'food_name': '홍화씨'},

            # 견과종실류 - 음료 및 감미종실류
            {'main_category': '견과종실류', 'sub_category': '음료및감미종실류', 'food_name': '결명자'},
            {'main_category': '견과종실류', 'sub_category': '음료및감미종실류', 'food_name': '과라나'},
            {'main_category': '견과종실류', 'sub_category': '음료및감미종실류', 'food_name': '카카오원두'},
            {'main_category': '견과종실류', 'sub_category': '음료및감미종실류', 'food_name': '커피원두'},
            {'main_category': '견과종실류', 'sub_category': '음료및감미종실류', 'food_name': '콜라너트'},
            {'main_category': '견과종실류', 'sub_category': '음료및감미종실류', 'food_name': '헛개열매'},

            # 과일류 - 인과류
            {'main_category': '과일류', 'sub_category': '인과류', 'food_name': '감'},
            {'main_category': '과일류', 'sub_category': '인과류', 'food_name': '모과'},
            {'main_category': '과일류', 'sub_category': '인과류', 'food_name': '배'},
            {'main_category': '과일류', 'sub_category': '인과류', 'food_name': '비파'},
            {'main_category': '과일류', 'sub_category': '인과류', 'food_name': '사과'},
            {'main_category': '과일류', 'sub_category': '인과류', 'food_name': '석류'},

            # 과일류 - 감귤류
            {'main_category': '과일류', 'sub_category': '감귤류', 'food_name': '감귤'},
            {'main_category': '과일류', 'sub_category': '감귤류', 'food_name': '금귤'},
            {'main_category': '과일류', 'sub_category': '감귤류', 'food_name': '레몬'},
            {'main_category': '과일류', 'sub_category': '감귤류', 'food_name': '라임'},
            {'main_category': '과일류', 'sub_category': '감귤류', 'food_name': '시트론'},
            {'main_category': '과일류', 'sub_category': '감귤류', 'food_name': '오렌지'},
            {'main_category': '과일류', 'sub_category': '감귤류', 'food_name': '유자'},
            {'main_category': '과일류', 'sub_category': '감귤류', 'food_name': '자몽'},
            {'main_category': '과일류', 'sub_category': '감귤류', 'food_name': '탱자'},

            # 과일류 - 핵과류
            {'main_category': '과일류', 'sub_category': '핵과류', 'food_name': '대추'},
            {'main_category': '과일류', 'sub_category': '핵과류', 'food_name': '매실'},
            {'main_category': '과일류', 'sub_category': '핵과류', 'food_name': '복숭아'},
            {'main_category': '과일류', 'sub_category': '핵과류', 'food_name': '산수유'},
            {'main_category': '과일류', 'sub_category': '핵과류', 'food_name': '살구'},
            {'main_category': '과일류', 'sub_category': '핵과류', 'food_name': '앵두'},
            {'main_category': '과일류', 'sub_category': '핵과류', 'food_name': '오미자'},
            {'main_category': '과일류', 'sub_category': '핵과류', 'food_name': '자두'},
            {'main_category': '과일류', 'sub_category': '핵과류', 'food_name': '체리'},

            # 과일류 - 장과류
            {'main_category': '과일류', 'sub_category': '장과류', 'food_name': '구기자'},
            {'main_category': '과일류', 'sub_category': '장과류', 'food_name': '꾸지뽕열매'},
            {'main_category': '과일류', 'sub_category': '장과류', 'food_name': '다래'},
            {'main_category': '과일류', 'sub_category': '장과류', 'food_name': '딸기'},
            {'main_category': '과일류', 'sub_category': '장과류', 'food_name': '마가목열매'},
            {'main_category': '과일류', 'sub_category': '장과류', 'food_name': '무화과'},
            {'main_category': '과일류', 'sub_category': '장과류', 'food_name': '블루베리'},
            {'main_category': '과일류', 'sub_category': '장과류', 'food_name': '빌베리'},
            {'main_category': '과일류', 'sub_category': '장과류', 'food_name': '복분자'},
            {'main_category': '과일류', 'sub_category': '장과류', 'food_name': '라즈베리'},
            {'main_category': '과일류', 'sub_category': '장과류', 'food_name': '블랙베리'},
            {'main_category': '과일류', 'sub_category': '장과류', 'food_name': '산딸기'},
            {'main_category': '과일류', 'sub_category': '장과류', 'food_name': '아로니아'},
            {'main_category': '과일류', 'sub_category': '장과류', 'food_name': '엘더베리'},
            {'main_category': '과일류', 'sub_category': '장과류', 'food_name': '오디'},
            {'main_category': '과일류', 'sub_category': '장과류', 'food_name': '커런트'},
            {'main_category': '과일류', 'sub_category': '장과류', 'food_name': '크랜베리'},
            {'main_category': '과일류', 'sub_category': '장과류', 'food_name': '으름'},
            {'main_category': '과일류', 'sub_category': '장과류', 'food_name': '포도'},
            {'main_category': '과일류', 'sub_category': '장과류', 'food_name': '머루'},

             # 과일류 - 열대과일류
            {'main_category': '과일류', 'sub_category': '열대과일류', 'food_name': '가시여지/그라비올라(열매)'},
            {'main_category': '과일류', 'sub_category': '열대과일류', 'food_name': '그라비올라(열매)'},
            {'main_category': '과일류', 'sub_category': '열대과일류', 'food_name': '구아바'},
            {'main_category': '과일류', 'sub_category': '열대과일류', 'food_name': '대추야자'},
            {'main_category': '과일류', 'sub_category': '열대과일류', 'food_name': '두리안'},
            {'main_category': '과일류', 'sub_category': '열대과일류', 'food_name': '리치'},
            {'main_category': '과일류', 'sub_category': '열대과일류', 'food_name': '망고'},
            {'main_category': '과일류', 'sub_category': '열대과일류', 'food_name': '망고스틴'},
            {'main_category': '과일류', 'sub_category': '열대과일류', 'food_name': '바나나'},
            {'main_category': '과일류', 'sub_category': '열대과일류', 'food_name': '바라밀'},
            {'main_category': '과일류', 'sub_category': '열대과일류', 'food_name': '잭프루트'},
            {'main_category': '과일류', 'sub_category': '열대과일류', 'food_name': '아보카도'},
            {'main_category': '과일류', 'sub_category': '열대과일류', 'food_name': '아사이팜'},
            {'main_category': '과일류', 'sub_category': '열대과일류', 'food_name': '아세로라'},
            {'main_category': '과일류', 'sub_category': '열대과일류', 'food_name': '용과'},
            {'main_category': '과일류', 'sub_category': '열대과일류', 'food_name': '용안'},
            {'main_category': '과일류', 'sub_category': '열대과일류', 'food_name': '코코넛'},
            {'main_category': '과일류', 'sub_category': '열대과일류', 'food_name': '키위'},
            {'main_category': '과일류', 'sub_category': '열대과일류', 'food_name': '참다래'},
            {'main_category': '과일류', 'sub_category': '열대과일류', 'food_name': '파인애플'},
            {'main_category': '과일류', 'sub_category': '열대과일류', 'food_name': '파파야'},
            {'main_category': '과일류', 'sub_category': '열대과일류', 'food_name': '패션 프루트'},
            {'main_category': '과일류', 'sub_category': '열대과일류', 'food_name': '포포나무(열매)'},

            # 채소류 - 결구엽채류
            {'main_category': '채소류', 'sub_category': '결구엽채류', 'food_name': '배추'},
            {'main_category': '채소류', 'sub_category': '결구엽채류', 'food_name': '브로콜리'},
            {'main_category': '채소류', 'sub_category': '결구엽채류', 'food_name': '콜리플라워'},
            {'main_category': '채소류', 'sub_category': '결구엽채류', 'food_name': '양배추'},
            {'main_category': '채소류', 'sub_category': '결구엽채류', 'food_name': '방울다다기양배추'},

            # 채소류 - 엽채류
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '갓'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '갯기름나물'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '방풍나물'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '겨자채'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '경수채'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '교나'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '고들빼기'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '고려엉겅퀴'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '곤드레나물'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '고추냉이(잎)'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '고춧잎'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '곤달비'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '공심채'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '근대'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '꾸지뽕(잎)'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '냉이'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '눈개승마'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '삼나물'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '뉴그린'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '다채'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '비타민'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '다청채'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '당귀(잎)'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '돌나물'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '둥굴레(잎)'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '들깻잎'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '라디치오'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '루꼴라'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '로케트'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '머위'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '무'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '민들레'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '배암차즈기'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '곰보배추'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '비름나물'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '비트(잎)'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '뽕(잎)'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '산마늘'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '명이나물(잎)'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '상추'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '쑥부쟁이'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '섬쑥부쟁이'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '부지깽이나물'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '순무유채'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '시금치'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '신선초'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '쑥'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '쑥갓'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '씀바귀'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '아욱'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '양상추'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '어수리'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '엇갈이배추'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '봄동'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '쌈배추'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '엉겅퀴'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '왕고들빼기'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '우엉(잎)'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '원추리'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '위트루프'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '치콘'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '유채'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '동초'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '질경이(잎)'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '차즈기'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '차조기'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '자소엽(잎)'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '참나물'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '청경채'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '춘채'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '취나물'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '곰취'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '미역취'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '참취'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '치커리(잎)'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '앤디브'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '케일'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '파드득나물'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '삼엽채'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '파슬리'},
            {'main_category': '채소류', 'sub_category': '엽채류', 'food_name': '호박(잎)'},

            # 채소류 - 엽경채류
            {'main_category': '채소류', 'sub_category': '엽경채류', 'food_name': '갯개미자리'},
            {'main_category': '채소류', 'sub_category': '엽경채류', 'food_name': '세발나물'},
            {'main_category': '채소류', 'sub_category': '엽경채류', 'food_name': '고구마(줄기)'},
            {'main_category': '채소류', 'sub_category': '엽경채류', 'food_name': '고비'},
            {'main_category': '채소류', 'sub_category': '엽경채류', 'food_name': '고사리'},
            {'main_category': '채소류', 'sub_category': '엽경채류', 'food_name': '달래'},
            {'main_category': '채소류', 'sub_category': '엽경채류', 'food_name': '두릅'},
            {'main_category': '채소류', 'sub_category': '엽경채류', 'food_name': '락교'},
            {'main_category': '채소류', 'sub_category': '엽경채류', 'food_name': '염교'},
            {'main_category': '채소류', 'sub_category': '엽경채류', 'food_name': '리크'},
            {'main_category': '채소류', 'sub_category': '엽경채류', 'food_name': '미나리'},
            {'main_category': '채소류', 'sub_category': '엽경채류', 'food_name': '부추'},
            {'main_category': '채소류', 'sub_category': '엽경채류', 'food_name': '삼채'},
            {'main_category': '채소류', 'sub_category': '엽경채류', 'food_name': '셀러리'},
            {'main_category': '채소류', 'sub_category': '엽경채류', 'food_name': '아스파라거스'},
            {'main_category': '채소류', 'sub_category': '엽경채류', 'food_name': '죽순'},
            {'main_category': '채소류', 'sub_category': '엽경채류', 'food_name': '콜라비'},
            {'main_category': '채소류', 'sub_category': '엽경채류', 'food_name': '토란(줄기)'},
            {'main_category': '채소류', 'sub_category': '엽경채류', 'food_name': '파'},
            {'main_category': '채소류', 'sub_category': '엽경채류', 'food_name': '쪽파'},
            {'main_category': '채소류', 'sub_category': '엽경채류', 'food_name': '풋마늘'},
            {'main_category': '채소류', 'sub_category': '엽경채류', 'food_name': '마늘종'},


            # 채소류 - 근채류
            {'main_category': '채소류', 'sub_category': '근채류', 'food_name': '고추냉이(뿌리)'},
            {'main_category': '채소류', 'sub_category': '근채류', 'food_name': '당근'},
            {'main_category': '채소류', 'sub_category': '근채류', 'food_name': '더덕'},
            {'main_category': '채소류', 'sub_category': '근채류', 'food_name': '도라지'},
            {'main_category': '채소류', 'sub_category': '근채류', 'food_name': '둥굴레(뿌리)'},
            {'main_category': '채소류', 'sub_category': '근채류', 'food_name': '마늘'},
            {'main_category': '채소류', 'sub_category': '근채류', 'food_name': '무(뿌리)'},
            {'main_category': '채소류', 'sub_category': '근채류', 'food_name': '물방기(뿌리)'},
            {'main_category': '채소류', 'sub_category': '근채류', 'food_name': '비트'},
            {'main_category': '채소류', 'sub_category': '근채류', 'food_name': '사탕무'},
            {'main_category': '채소류', 'sub_category': '근채류', 'food_name': '생강'},
            {'main_category': '채소류', 'sub_category': '근채류', 'food_name': '셀러리악'},
            {'main_category': '채소류', 'sub_category': '근채류', 'food_name': '수삼'},
            {'main_category': '채소류', 'sub_category': '근채류', 'food_name': '산양삼'},
            {'main_category': '채소류', 'sub_category': '근채류', 'food_name': '순무'},
            {'main_category': '채소류', 'sub_category': '근채류', 'food_name': '양파'},
            {'main_category': '채소류', 'sub_category': '근채류', 'food_name': '연근'},
            {'main_category': '채소류', 'sub_category': '근채류', 'food_name': '우엉'},
            {'main_category': '채소류', 'sub_category': '근채류', 'food_name': '참나리'},
            {'main_category': '채소류', 'sub_category': '근채류', 'food_name': '비늘줄기'},
            {'main_category': '채소류', 'sub_category': '근채류', 'food_name': '참나리(뿌리)'},
            {'main_category': '채소류', 'sub_category': '근채류', 'food_name': '치커리(뿌리)'},
            {'main_category': '채소류', 'sub_category': '근채류', 'food_name': '파스닙'},

            # 채소류 - 박과과채류
            {'main_category': '채소류', 'sub_category': '박과과채류', 'food_name': '멜론'},
            {'main_category': '채소류', 'sub_category': '박과과채류', 'food_name': '박'},
            {'main_category': '채소류', 'sub_category': '박과과채류', 'food_name': '수박'},
            {'main_category': '채소류', 'sub_category': '박과과채류', 'food_name': '여주'},
            {'main_category': '채소류', 'sub_category': '박과과채류', 'food_name': '오이'},
            {'main_category': '채소류', 'sub_category': '박과과채류', 'food_name': '참외'},
            {'main_category': '채소류', 'sub_category': '박과과채류', 'food_name': '호박'},

            # 채소류 - 박과이외과채류
            {'main_category': '채소류', 'sub_category': '박과이외과채류', 'food_name': '가지'},
            {'main_category': '채소류', 'sub_category': '박과이외과채류', 'food_name': '고추'},
            {'main_category': '채소류', 'sub_category': '박과이외과채류', 'food_name': '오크라'},
            {'main_category': '채소류', 'sub_category': '박과이외과채류', 'food_name': '토마토'},
            {'main_category': '채소류', 'sub_category': '박과이외과채류', 'food_name': '방울토마토'},
            {'main_category': '채소류', 'sub_category': '박과이외과채류', 'food_name': '풋콩'},
            {'main_category': '채소류', 'sub_category': '박과이외과채류', 'food_name': '꼬투리포함된그린빈'},
            {'main_category': '채소류', 'sub_category': '박과이외과채류', 'food_name': '대두'},
            {'main_category': '채소류', 'sub_category': '박과이외과채류', 'food_name': '스냅빈'},
            {'main_category': '채소류', 'sub_category': '박과이외과채류', 'food_name': '완두'},
            {'main_category': '채소류', 'sub_category': '박과이외과채류', 'food_name': '피망'},
            {'main_category': '채소류', 'sub_category': '박과이외과채류', 'food_name': '파프리카'},

            # 버섯류
            {'main_category': '버섯류', 'food_name': '갓버섯'},
            {'main_category': '버섯류', 'food_name': '꽃송이버섯'},
            {'main_category': '버섯류', 'food_name': '나도팽나무버섯/맛버섯'},
            {'main_category': '버섯류', 'food_name': '느타리버섯'},
            {'main_category': '버섯류', 'food_name': '목이버섯'},
            {'main_category': '버섯류', 'food_name': '목질진흙버섯'},
            {'main_category': '버섯류', 'food_name': '상황버섯'},
            {'main_category': '버섯류', 'food_name': '새송이버섯'},
            {'main_category': '버섯류', 'food_name': '석이버섯'},
            {'main_category': '버섯류', 'food_name': '송이버섯'},
            {'main_category': '버섯류', 'food_name': '신령버섯'},
            {'main_category': '버섯류', 'food_name': '싸리버섯'},
            {'main_category': '버섯류', 'food_name': '양송이버섯'},
            {'main_category': '버섯류', 'food_name': '영지버섯'},
            {'main_category': '버섯류', 'food_name': '팽이버섯'},
            {'main_category': '버섯류', 'food_name': '표고버섯'},
            {'main_category': '버섯류', 'food_name': '황금뿔나팔버섯'},

            # 향신식물 - 허브류
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '가시여지'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '그라비올라(가지)'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '그라비올라(잎)'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '고수(잎)'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '돌외(잎)'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '드럼스틱'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '모링가(잎)'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '모링가(줄기)'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '라벤더'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '레몬그라스'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '레몬머틀'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '레몬밤'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '로즈마리'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '루이보스'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '마타리(순)'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '마테(잎)'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '민트'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '박하'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '서양박하'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '페퍼민트'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '스피어민트'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '애플민트'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '밀크씨슬(잎)'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '바질(잎)'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '배초향'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '방아잎'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '사향초'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '백리향'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '서양자초'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '딜(잎)'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '스테비아'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '식용꽃'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '국화'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '금잔화'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '마리골드'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '장미'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '캐모마일'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '히비스커스'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '아이언워트'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '오레가노'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '올리브(잎)'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '월계수'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '쟈스민'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '초피나무'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '쿨란트로'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '타임'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '허니부쉬'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '호로파(잎)'},
            {'main_category': '향신식물', 'sub_category': '허브류', 'food_name': '회향(잎)'},

            # 향신식물 - 향신열매
            {'main_category': '향신식물', 'sub_category': '향신열매', 'food_name': '노간주나무(열매)'},
            {'main_category': '향신식물', 'sub_category': '향신열매', 'food_name': '바닐라(열매)'},
            {'main_category': '향신식물', 'sub_category': '향신열매', 'food_name': '백미후추(열매)'},
            {'main_category': '향신식물', 'sub_category': '향신열매', 'food_name': '산초(열매)'},
            {'main_category': '향신식물', 'sub_category': '향신열매', 'food_name': '소두구(열매)'},
            {'main_category': '향신식물', 'sub_category': '향신열매', 'food_name': '스타아니스'},
            {'main_category': '향신식물', 'sub_category': '향신열매', 'food_name': '팔각회향(열매)'},
            {'main_category': '향신식물', 'sub_category': '향신열매', 'food_name': '케이퍼(열매)'},
            {'main_category': '향신식물', 'sub_category': '향신열매', 'food_name': '후추(열매)'},

            # 향신식물 - 향신씨
            {'main_category': '향신식물', 'sub_category': '향신씨', 'food_name': '겨자(씨)'},
            {'main_category': '향신식물', 'sub_category': '향신씨', 'food_name': '고수(씨)'},
            {'main_category': '향신식물', 'sub_category': '향신씨', 'food_name': '밀크씨슬(씨)'},
            {'main_category': '향신식물', 'sub_category': '향신씨', 'food_name': '바질(씨)'},
            {'main_category': '향신식물', 'sub_category': '향신씨', 'food_name': '서양자초'},
            {'main_category': '향신식물', 'sub_category': '향신씨', 'food_name': '딜(씨)'},
            {'main_category': '향신식물', 'sub_category': '향신씨', 'food_name': '셀러리(씨)'},
            {'main_category': '향신식물', 'sub_category': '향신씨', 'food_name': '아니스(씨)'},
            {'main_category': '향신식물', 'sub_category': '향신씨', 'food_name': '육두구(씨)'},
            {'main_category': '향신식물', 'sub_category': '향신씨', 'food_name': '차즈기'},
            {'main_category': '향신식물', 'sub_category': '향신씨', 'food_name': '차조기'},
            {'main_category': '향신식물', 'sub_category': '향신씨', 'food_name': '자소자(씨)'},
            {'main_category': '향신식물', 'sub_category': '향신씨', 'food_name': '캐러웨이(씨)'},
            {'main_category': '향신식물', 'sub_category': '향신씨', 'food_name': '쿠민(씨)'},
            {'main_category': '향신식물', 'sub_category': '향신씨', 'food_name': '호로파(씨)'},
            {'main_category': '향신식물', 'sub_category': '향신씨', 'food_name': '회향(씨)'},

            # 향신식물 - 향신뿌리
            {'main_category': '향신식물', 'sub_category': '향신뿌리', 'food_name': '강황'},
            {'main_category': '향신식물', 'sub_category': '향신뿌리', 'food_name': '심황'},
            {'main_category': '향신식물', 'sub_category': '향신뿌리', 'food_name': '울금(뿌리)'},

            # 향신식물 - 기타향신식물
            {'main_category': '향신식물', 'sub_category': '기타향신식물', 'food_name': '계피(가지)'},
            {'main_category': '향신식물', 'sub_category': '기타향신식물', 'food_name': '계피(줄기껍질)'},
            {'main_category': '향신식물', 'sub_category': '기타향신식물', 'food_name': '몰약'},
            {'main_category': '향신식물', 'sub_category': '기타향신식물', 'food_name': '고무수지'},
            {'main_category': '향신식물', 'sub_category': '기타향신식물', 'food_name': '사프란'},
            {'main_category': '향신식물', 'sub_category': '기타향신식물', 'food_name': '암술머리'},
            {'main_category': '향신식물', 'sub_category': '기타향신식물', 'food_name': '정향'},
            {'main_category': '향신식물', 'sub_category': '기타향신식물', 'food_name': '꽃봉오리'},

            # 차
            {'main_category': '차', 'food_name': '차'},

            # 호프
            {'main_category': '호프', 'food_name': '호프'},

            # 조류 - 해조류
            {'main_category': '조류', 'sub_category': '해조류', 'food_name': '갈래곰보'},
            {'main_category': '조류', 'sub_category': '해조류', 'food_name': '갈파래'},
            {'main_category': '조류', 'sub_category': '해조류', 'food_name': '곰피'},
            {'main_category': '조류', 'sub_category': '해조류', 'food_name': '김'},
            {'main_category': '조류', 'sub_category': '해조류', 'food_name': '꼬시래기'},
            {'main_category': '조류', 'sub_category': '해조류', 'food_name': '다시마'},
            {'main_category': '조류', 'sub_category': '해조류', 'food_name': '돌가사리'},
            {'main_category': '조류', 'sub_category': '해조류', 'food_name': '둥근돌김'},
            {'main_category': '조류', 'sub_category': '해조류', 'food_name': '뜸부기'},
            {'main_category': '조류', 'sub_category': '해조류', 'food_name': '매생이'},
            {'main_category': '조류', 'sub_category': '해조류', 'food_name': '모자반'},
            {'main_category': '조류', 'sub_category': '해조류', 'food_name': '미역'},
            {'main_category': '조류', 'sub_category': '해조류', 'food_name': '불등가사리'},
            {'main_category': '조류', 'sub_category': '해조류', 'food_name': '석묵'},
            {'main_category': '조류', 'sub_category': '해조류', 'food_name': '우뭇가사리'},
            {'main_category': '조류', 'sub_category': '해조류', 'food_name': '진두발'},
            {'main_category': '조류', 'sub_category': '해조류', 'food_name': '청각'},
            {'main_category': '조류', 'sub_category': '해조류', 'food_name': '톳'},
            {'main_category': '조류', 'sub_category': '해조류', 'food_name': '파래'},

            # 기타 식물류
            {'main_category': '기타 식물류', 'food_name': '단수수'},
            {'main_category': '기타 식물류', 'food_name': '마가목(껍질)'},
            {'main_category': '기타 식물류', 'food_name': '사탕수수'}

        ]

        for data in categories_data:
            FoodCategory.objects.create(**data)

        self.stdout.write(self.style.SUCCESS('성공적으로 데이터를 가져왔습니다.'))
